[package]
name = "lapce-zig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.22"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
lapce-plugin = "0.1.0"