name = "lapce-zig"
display-name = "Zig"
description = "Zig for Lapce: powered by Zig Language Server"
version = "0.1.1"
author = "Lapce"
repository = "ghishadow/lapce-zig"
wasm = "lapce-zig.wasm"

[configuration]
language_id = "zig"
env_command = "zig env"
system_lsp = true
enabled = true

[configuration.options]
scopes = ["source.zig"]
semanticTokens = true
roots = ["build.zig"]
[configuration.options.diagnostics]
enable = true
enableExperimental = true

[configuration.options.binary]
args = []
