name = "lapce-haskell"
display-name = "Haskell"
description = "Haskell for Lapce: powered by Haskell Language Server"
version = "0.0.1" 
author = "MangoIV"
repository = "mangoiv/lapce-haskell"
icon = "assets/haskell.svg"
wasm = "lapce-haskell.wasm"


[activation]
language = ["haskell"]


[config."serverPath"]
default = ""
description = "Path to hls executable. When empty, it uses the haskell-language-server-wrapper currently in $PATH"
