name = "lapce-zig"
display-name = "Zig"
description = "Zig for Lapce: powered by Zig Language Server"
version = "0.1.1"
author = "Lapce"
repository = "ghishadow/lapce-zig"
wasm = "lapce-zig.wasm"


[activation]
language = ["zig"]
workspace-contains = ["*/build.zig"]



[config."serverPath"]
default = ""
description = "Path to zls executable. When empty, it points to the bundled binary."

[config."diagnostics.enable"]
default = true
description = "Whether to show native zls diagnostics."

[config."diagnostics.experimental.enable"]
default = true
description = "Whether to show native zls diagnostics."

[config."checkOnSave.command"]
default = "check"
description = "Zig command to format"